# Generated by Django 3.1.1 on 2020-12-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.userroom'),
        ),
    ]
