# Generated by Django 3.0.5 on 2020-04-11 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("prosocial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppro",
            name="description",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("facebook", models.CharField(blank=True, max_length=50, null=True)),
                ("role", models.SmallIntegerField()),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "assigned_user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="comment",
            name="userId",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="prosocial.Member",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="userId",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="prosocial.Member",
            ),
        ),
    ]
