# Generated by Django 3.0.5 on 2020-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prosocial", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="custommember",
            name="avatar",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
