# Generated by Django 3.0.5 on 2020-04-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prosocial", "0002_auto_20200411_1906"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="postId", new_name="assigned_post",
        ),
        migrations.RenameField(
            model_name="comment", old_name="userId", new_name="assigned_user",
        ),
        migrations.RenameField(
            model_name="post", old_name="groupId", new_name="assigned_group",
        ),
        migrations.RenameField(
            model_name="post", old_name="userId", new_name="assigned_user",
        ),
        migrations.AddField(
            model_name="grouppro",
            name="admins",
            field=models.ManyToManyField(related_name="admins", to="prosocial.Member"),
        ),
        migrations.AddField(
            model_name="grouppro",
            name="members",
            field=models.ManyToManyField(related_name="members", to="prosocial.Member"),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            ("LIKE", 0),
                            ("HEART", 1),
                            ("HAHA", 2),
                            ("WOW", 3),
                            ("ANGRY", 4),
                        ],
                        null=True,
                    ),
                ),
                (
                    "assigned_post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prosocial.Post",
                    ),
                ),
                (
                    "assigned_user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prosocial.Member",
                    ),
                ),
            ],
        ),
    ]
