# Generated by Django 3.0.2 on 2020-04-17 02:44

from django.db import migrations, models
import prosocial.models


class Migration(migrations.Migration):

    dependencies = [
        ("prosocial", "0002_custommember_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custommember",
            name="avatar",
            field=models.FileField(
                default="default.jpg", upload_to=prosocial.models.custom_media_path
            ),
        ),
    ]
