# Generated by Django 3.0.5 on 2020-04-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prosocial", "0003_auto_20200412_1316"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouppro",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="members",
                to="prosocial.Member",
            ),
        ),
    ]
