# Generated by Django 3.0.5 on 2020-04-12 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("prosocial", "0004_auto_20200412_1330"),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1024)),
                (
                    "assigned_post",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prosocial.Post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tick",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=1024)),
                (
                    "assigned_poll",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prosocial.Poll",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, default=None, null=True, to="prosocial.Member"
                    ),
                ),
            ],
        ),
    ]
