# Generated by Django 3.0.5 on 2020-04-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prosocial", "0005_poll_tick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "LIKE"),
                    (1, "HEART"),
                    (2, "HAHA"),
                    (3, "WOW"),
                    (4, "ANGRY"),
                ],
                null=True,
            ),
        ),
    ]
