# Generated by Django 3.0.2 on 2020-05-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0007_auto_20200502_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custommember',
            name='gender',
        ),
        migrations.AddField(
            model_name='custommember',
            name='user_gender',
            field=models.SmallIntegerField(choices=[(1, 'MALE'), (0, 'FEMALE'), (2, 'OTHER')], default=1),
        ),
    ]
