# Generated by Django 3.0.5 on 2020-06-07 09:46

from django.db import migrations, models
import prosocial.models


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0009_remove_tick_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppro',
            name='avatar',
            field=models.FileField(default='default.jpg', upload_to=prosocial.models.custom_media_path),
        ),
    ]
