# Generated by Django 3.0.2 on 2020-08-26 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0012_notification_notificationmember_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
