# Generated by Django 3.0.2 on 2020-08-30 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0014_bonuspoint_point_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tick',
            name='users',
        ),
        migrations.AddField(
            model_name='tick',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
