# Generated by Django 3.0.2 on 2020-09-01 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0015_auto_20200830_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
