# Generated by Django 3.0.2 on 2020-09-03 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0016_post_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
