# Generated by Django 3.0.2 on 2020-09-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0018_auto_20200903_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='created_time',
            field=models.DateTimeField(),
        ),
    ]
