# Generated by Django 3.0.2 on 2020-09-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0019_auto_20200903_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tick',
            old_name='user',
            new_name='assigned_user',
        ),
    ]
