# Generated by Django 3.1.1 on 2020-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0020_auto_20200905_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommember',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='target',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
