# Generated by Django 3.1.1 on 2020-10-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0021_auto_20201002_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prosocial.point'),
        ),
    ]
