# Generated by Django 3.1.1 on 2020-10-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0022_auto_20201002_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='created_time',
            field=models.DateTimeField(null=True),
        ),
    ]
