# Generated by Django 3.1.1 on 2021-01-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0024_target_result_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(max_length=1000),
        ),
    ]
