# Generated by Django 3.1.1 on 2021-02-08 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0026_lixi'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('assigned_user', 'device_id')},
        ),
    ]
