# Generated by Django 3.1.1 on 2021-02-16 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prosocial', '0027_auto_20210208_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MemberSpecialRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.SmallIntegerField(choices=[(0, 'BLOCK')], default=0)),
                ('another', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='another', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
